listener 1883
allow_anonymous true

listener 8883
allow_anonymous true
cafile   /mosquitto/certs/ca.pem
certfile /mosquitto/certs/server.pem
keyfile  /mosquitto/certs/server.key
require_certificate true
log_type all
